# Generated by Django 5.0 on 2024-02-05 16:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('article', models.CharField(max_length=512, verbose_name='Article')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Blog Image')),
                ('number_of_view', models.PositiveIntegerField(default=0, verbose_name='Number of Views')),
                ('publication_date', models.DateField(verbose_name='Publication Date')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('surname', models.CharField(max_length=64, verbose_name='Surname')),
                ('comment', models.TextField(verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ('email',),
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date & Time')),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('finished', 'Finished')], max_length=24, verbose_name='Status')),
                ('server_response', models.TextField(verbose_name='Server response')),
                ('email_subject', models.CharField(blank=True, max_length=256, null=True, verbose_name='Email Subject')),
                ('email_body', models.TextField(blank=True, null=True, verbose_name='Email Body')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailings.client')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256, verbose_name='E-mail subject')),
                ('body', models.TextField(verbose_name='E-mail body')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mailings.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Starting date')),
                ('mailing_time', models.TimeField(blank=True, null=True, verbose_name='Mailing time')),
                ('periodicity', models.CharField(choices=[('daily', 'Once a day'), ('weekly', 'Once a week'), ('monthly', 'Once a month')], max_length=12, verbose_name='Periodicity')),
                ('mailing_status', models.CharField(max_length=24, verbose_name='Mailing status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='mailings.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
